version: "3"

tasks:
  generate:
    cmds:
      - go tool -modfile=go.tool.mod buf generate

  docs:
    cmds:
      - go tool -modfile=go.tool.mod buf build -o example.protoset
      - grpcui -plaintext -protoset=example.protoset 127.0.0.1:9090
